include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
    unused_import: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: false
    prefer_const_declarations: false
    use_key_in_widget_constructors: false
    unawaited_futures: false
